#!/bin/bash

SELF=${0##*/}
REALPATH=$(dirname "$(realpath "$0")")

pink="\e[38;5;211m"
red="\e[38;5;204m"
blue="\e[38;5;111m"
end="\e[0m"

function __cmd_file(){
  if [[ -f "${REALPATH}/src/scripts/file" ]]; then
      source "${REALPATH}/src/scripts/file"
      cmd_file "${@}" 
  else
      echo "Error: script 'file' not found in ${REALPATH}/src/scripts/"
  fi
}

function __messagebox(){
  if [[ -f "${REALPATH}/src/scripts/messagebox" ]]; then
      source "${REALPATH}/src/scripts/messagebox"
      messagebox "${@}"
  else
      echo "Error: script 'messagebox' not found"
  fi
}

function __confirm(){
  if [[ -f "${REALPATH}/src/scripts/confirm" ]]; then
      source "${REALPATH}/src/scripts/confirm"
      cmd_confirm "${@}"
  else
      echo "Error: script 'confirm' not found"
  fi
}

function __choose(){
  
  if [[ -f "${REALPATH}/src/scripts/choose" ]]; then 
    source "${REALPATH}/src/scripts/choose"
    cmd_choose "${@}"
  else 
    echo "Error: script 'choose' not found"
  fi 
}

function __spin(){
  if [[ -f "${REALPATH}/src/scripts/spin" ]]; then 
    source "${REALPATH}/src/scripts/spin"
    cmd_spin "${@}"
  else 
    echo "Error: script 'spin' not found"
  fi 
}

function __input(){
  if [[ -f "${REALPATH}/src/scripts/input" ]]; then 
    source "${REALPATH}/src/scripts/input"
    cmd_input "${@}"
  else 
    echo "Error: script 'input' not found"
  fi 
}

function __write(){
  if [[ -f "${REALPATH}/src/scripts/write" ]]; then 
    source "${REALPATH}/src/scripts/write"
    cmd_write "${@}"
  else 
    echo "Error: script 'write' not found"
  fi 
}

function __filter(){
  if [[ -f "${REALPATH}/src/scripts/filter" ]]; then 
    source "${REALPATH}/src/scripts/filter"
    cmd_filter "${@}"
  else 
    echo "Error: script 'filter' not found"
  fi 
}

function __log(){
  if [[ -f "${REALPATH}/src/scripts/log" ]]; then 
    source "${REALPATH}/src/scripts/log"
    cmd_log "${@}"
  else 
    echo "Error: script 'log' not found"
  fi 
}

function __style(){
  if [[ -f "${REALPATH}/src/scripts/style" ]]; then 
    source "${REALPATH}/src/scripts/style"
    cmd_style "${@}"
  else 
    echo "Error: script 'style' not found"
  fi 
}

function __text(){
  if [[ -f "${REALPATH}/src/scripts/text" ]]; then 
    source "${REALPATH}/src/scripts/text"
    cmd_text "${@}"
  else 
    echo "Error: 'text' not found"
  fi 
}

function __table(){
  if [[ -f "${REALPATH}/src/scripts/table" ]]; then 
    source "${REALPATH}/src/scripts/table"
    cmd_table "${@}"
  else 
    echo "Error: 'table' not found"
  fi 
}

function __pager(){
    if [[ -f "${REALPATH}/src/scripts/pager" ]]; then 
        source "${REALPATH}/src/scripts/pager"
        cmd_pager "${@}"
    else
        echo "Error: 'table' not found"
    fi
}

function __join(){
  if [[ -f "${REALPATH}/src/scripts/join" ]]; then 
    source "${REALPATH}/src/scripts/join"
    cmd_join "${@}"
  else 
    echo "Error: 'join' not found"
  fi 
}

function __format(){
  if [[ -f "${REALPATH}/src/scripts/format" ]]; then 
    source "${REALPATH}/src/scripts/format"
    cmd_format "${@}"
  else 
    echo "Error: 'format' not found"
  fi 
}

function helpPanel(){
  msg="Usage: ${SELF} <command> [flags]

A tool for ${pink}shell scripts${end}.

Flags:
  -h, --help        Show context-sensitive help.
  -v, --version     Print the version number

Commands:
  ${blue}choose${end}             Choose an option from a list of choices
  ${blue}confirm${end}            Ask a user to confirm an action
  ${blue}file${end}               Pick a file from a folder
  ${blue}messagebox${end}         Display a message box
  ${blue}spin${end}               Display spinner while running a command
  ${blue}write${end}              Prompt for long-form text
  ${blue}input${end}              Prompt for some input
  ${blue}filter${end}             Filter items from a list
  ${blue}log${end}                Log messages to output
  ${blue}table${end}              Render a table of data
  ${blue}text${end}               Show a beautifiul text
  ${blue}style${end}              Apply coloring, borders, spacing to text
  ${blue}pager${end}              Scroll through a file
  ${blue}join${end}               Join text vertically or horizontally
  ${blue}format${end}             Format a string using a template

Run \"${SELF} <command> --help\" for more information on a command."""

  printf "%b\n" "${msg}"
  return 0 
} 


function main(){
  if [[ -z "$1" ]]; then
      helpPanel
      exit 1
  fi

  local subcmd="$1"
  shift 

  case "$subcmd" in
      file)
          __cmd_file "$@"
          ;;
      choose)
          __choose "$@"
          ;;
      confirm)
          __confirm "$@"
          ;;
      messagebox)
          __messagebox "${@}"
          ;;
      spin)
         __spin "${@}"
         ;; 
      write) 
        __write "${@}"
        ;;
      input)
        __input "${@}"
        ;; 
      filter)
        __filter "${@}"
        ;; 
      log)
        __log "${@}"
        ;; 
      style)
        __style "${@}"
        ;;
      text)
        __text "${@}"
        ;; 
      table) 
        __table "${@}"
        ;;
      pager)
        __pager "${@}"
        ;;
      join)
        __join "${@}"
        ;;
      format)
        __format "${@}"
        ;;
      -h|--help)
          helpPanel
          ;;
      -v|--version)
        printf "bash-utils version v0.0.1\n"
        return 0
        ;;
      *)
          helpPanel
          echo -e "\n${red}${SELF}: error: expected one of \"choose\", \"confirm\", \"file\", ...${end}\n"
          exit 1
          ;;
  esac
}

main "${@}"
